smallrye/jandex

src/main/java/org/jboss/jandex/JarIndexer.java
Do not copy existing jandex.idx to the output zip
=> JANDEX-29: Jandex fails to reindex index JAR file

pom.xml
The current name given to the license in pom.xml is "AL 2.0", which is more difficult to interpret than the more canonical "Apache License, Version 2.0".
Changing the name in the POM file effects the output of the License Maven Plugin (http://mojo.codehaus.org/license-maven-plugin/examples/example-thirdparty.html), making it easier to interpret the output of the add-third-party and aggregate-add-third-party goals.
I would have change the name to "The Apache Software License, Version 2.0", but that form is not found in the license itself.
=> Spell out the license name more verbosely

src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/BoundedWildcardTestCase.java
Updated version of #28 that is slightly more efficient
=> [JANDEX-35] Failure to resolve method type variable when using class-level bounded wildcard generics

src/main/java/org/jboss/jandex/ClassInfo.java, src/main/java/org/jboss/jandex/IndexReaderV1.java, src/main/java/org/jboss/jandex/IndexReaderV2.java, src/main/java/org/jboss/jandex/IndexWriterV2.java, src/main/java/org/jboss/jandex/Indexer.java, src/main/java/org/jboss/jandex/MethodInfo.java, src/main/java/org/jboss/jandex/MethodInternal.java, src/main/java/org/jboss/jandex/MethodParameterInfo.java, src/test/java/org/jboss/jandex/test/BasicTestCase.java
Support method parameter names:
- Bumped index version
- Read method param name attribute
- Default to debug info if missing
- Align method param name indices to method param annotation indices (not types)
This is pretty much required for RESTEasy extensions indexed by MP-OpenAPI
=> Method param names

README.md
due to `Duplicate local variable stream` and missed call to `index()`
=> Fix snippet which does not compile nor work

src/main/java/org/jboss/jandex/AnnotationValue.java
I noticed this typo while using this method from a Quarkus extension.
I'll let you judge whether or not this is reasonnable change considering it is a breaking change for anyone who's using the old method name.
=> Fix AnnotationValue methods names and Javadoc 

pom.xml
This PR bumps the version of the maven-enforcer-plugin so that it can cope with the version strings of modern JDKs and won't exit with an `ExceptionInInitializerError` when invoked.  It also sets an `Automatic-Module-Name` in the `META-INF/MANIFEST.MF` file.  I followed the module naming guidelines referenced by Stephen Coleburne here: https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html
This is obviously a stopgap measure until this library can be truly modularized but it at least "claims" the module name with no compatibility issues.
Signed-off-by: Laird Nelson <ljnelson@gmail.com>
=> Set Automatic-Module-Name and fix maven-enforcer-plugin problem

pom.xml, src/main/java/org/jboss/jandex/ClassInfo.java, src/main/java/org/jboss/jandex/CompositeIndex.java, src/main/java/org/jboss/jandex/FieldInfo.java, src/main/java/org/jboss/jandex/Index.java, src/main/java/org/jboss/jandex/IndexView.java, src/main/java/org/jboss/jandex/MethodInfo.java, src/test/java/org/jboss/jandex/test/RepeatableAnnotationsTestCase.java, src/test/java8/org/jboss/jandex/test/RepeatableAnnotationsTestCase.java
This is a POC for #67.
I've added several methods, most of them follow the naming and approach of `AnnotationInstance.valueWithDefault()`, i.e. the method declares an `IndexView` param that is used to obtain the annotation type definition and determine the repeatable annotation container (if present).
Note that `MethodInfo.annotationsWithRepeatable()` is a bit special because it should align with the contract of `MethodInfo.annotations()` which returns annotations declared on method or its parameters.
`IndexView.getAnnotationsWithRepeatable()` and `MethodInfo.annotationsWithRepeatable()`  are also special because they need to replace the target of the returned annotation instances for the ones coming from the container, otherwise it wouldn't be possible to determine the exact location of …
=> Repeatable annotations

pom.xml, src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/TypeParameterBoundTestCase.java
Java 8 javac generates an invalid type annotation path with duplicate entries on the tail for NESTED/INNER_CLASS elements of the type path when an anonymous inner class extends a type annotated generic type. This fix works around the issue by truncating the entries and hoping for the best. 
The error message now also includes the classname should it occur again.
Fixes #92
=> Workaround invalid bytecode generated by java8

src/main/java/org/jboss/jandex/DotName.java, src/test/java/org/jboss/jandex/test/DotNameTestCase.java
I needed this several times in the past when filtering classes by package name. This nicely completes the existing `withoutPackagePrefix()` method.
=> Add DotName.packagePrefix() method

src/main/java/org/jboss/jandex/Indexer.java
The bitsToLong method of Indexer class given wrong result when the bytes having the highest bit set. For example when I have a parameter annotation `@Max(19999999999L)`, the method converted it to `-1474836481L`. This pull request fix that problem.
=> bitsToLong given wrong result when the bytes having the highest bit set

src/main/java/org/jboss/jandex/ClassInfo.java, src/main/java/org/jboss/jandex/FieldInfoGenerator.java, src/main/java/org/jboss/jandex/IndexReaderV1.java, src/main/java/org/jboss/jandex/IndexReaderV2.java, src/main/java/org/jboss/jandex/IndexWriterV2.java, src/main/java/org/jboss/jandex/Indexer.java, src/main/java/org/jboss/jandex/MethodInfoGenerator.java, src/test/java/org/jboss/jandex/test/ClassInfoMemberPositionTestCase.java
Fixes #58 
Supersedes #61 
This change supports the storage of class member positions, as originally scanned from the byte stream. The positions are only utilized when client code requests a list of `unsortedFields` or `unsortedMethods`.
Indexing the rt.jar file from JRE 1.8.0_232 produces the following index size:
1. 4,836,637 bytes using release version 2.1.2.Final of Jandex
2. 5,237,838 bytes with the changes in this PR
A very simple test to load the two indexes shows that the version in this PR uses approximately 1,200k more heap memory (28,345,736 `main` thread Bytes) than 2.1.2.Final (27,128,488 `main` thread Bytes)
```java
public class Load {
public static void main(String[] args) throws Exception {
IndexReader reader = new IndexReader(new FileInputStream(args[0]));
Index index = …
```
=> Store original member positions for unsorted iteration

src/main/java/org/jboss/jandex/ClassInfo.java
@n1hility - thanks for pointing me in the right direction in your comment on #73. I took a look and it turns out that the binarySearch approach is in fact broken as it relates to bridge methods. I ran into some differences in the index testing with an `IdentityHashMap` and I believe it is a necessary change.
Consider class `com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.UUIDImpl` with the following methods:
```
void                   <init>()
java.util.UUID         parse(java.lang.CharSequence text) throws org.xml.sax.SAXException
java.lang.Object       parse(java.lang.CharSequence)      throws com.sun.xml.internal.bind.api.AccessorException, org.xml.sax.SAXException
java.lang.String       print(java.lang.Object)            throws …
```
=> Replace original positions binary search with `IdentityHashMap`

src/main/java/org/jboss/jandex/Index.java, src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/BasicTestCase.java
This PR adds several factory methods to `Index` and support for passing a `Class` directly to the `Indexer` with the intent of simplifying the creation of "mock" indexes in unit tests, etc.
=> Convenience methods for creating an Index

pom.xml, src/main/java/org/jboss/jandex/IndexReaderV2.java, src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/TypeAnnotationTestCase.java, src/test/java/org/jboss/jandex/test/TypeUseTestCase.java
See the reproducer for the detail of the problem I'm trying to fix. The problem was detected downstream in Quarkus: https://github.com/quarkusio/quarkus/issues/17491
See the message of the second-to-last commit for an explanation of the fix. Copying it here for convenience:
```quote
Include relevant type-use annotations in MethodInfo/FieldInfo
First, because that's what the javadoc of MethodInfo advertises.
For example in the javadoc of
org.jboss.jandex.MethodInfo#annotations(org.jboss.jandex.DotName):
* Retrieves annotations declared on this method, by the name of the
annotation. This includes annotations which are defined against
method parameters, as
* well as type annotations declared on any usage within the method
signature. The <code>target()</code> of the returned annotation …
```
=> Include relevant type-use annotations in MethodInfo/FieldInfo and fix index writing for TypeTarget

pom.xml, src/main/java/org/jboss/jandex/AnnotationTarget.java, src/main/java/org/jboss/jandex/ClassInfo.java, src/main/java/org/jboss/jandex/CompositeIndex.java, src/main/java/org/jboss/jandex/DotName.java, src/main/java/org/jboss/jandex/Index.java, src/main/java/org/jboss/jandex/IndexReaderV2.java, src/main/java/org/jboss/jandex/IndexView.java, src/main/java/org/jboss/jandex/IndexWriterV2.java, src/main/java/org/jboss/jandex/Indexer.java, src/main/java/org/jboss/jandex/MethodInfo.java, src/main/java/org/jboss/jandex/MethodInternal.java, src/main/java/org/jboss/jandex/MethodParameterInfo.java, src/main/java/org/jboss/jandex/ModuleInfo.java, src/main/java/org/jboss/jandex/NameTable.java, src/main/java/org/jboss/jandex/RecordComponentInfo.java, src/main/java/org/jboss/jandex/RecordComponentInfoGenerator.java, src/main/java/org/jboss/jandex/RecordComponentInternal.java, src/main/java/org/jboss/jandex/TypeTarget.java, src/main/java/org/jboss/jandex/Utils.java, src/test/java/org/jboss/jandex/test/AnnotationInstanceFilterTestCase.java, src/test/java/org/jboss/jandex/test/ModuleInfoTestCase.java, src/test/java/org/jboss/jandex/test/RecordTestCase.java, src/test/java/org/jboss/jandex/test/TypeAnnotationTestCase.java
Adds support for the scanning of `module-info` class files (JDK 9+) as well as annotations on record components (GA JDK 16).
- New `ModuleInfo` model referenced from its parent `ClassInfo`'s `nestingInfo`. Annotations from the Java `module` are still present on the `ClassInfo`, but having the `ModuleInfo` model with the descriptor details is a "nice to have" to support other potential use cases
- Index modules separately from classes
- Add `AnnotationTarget.Kind.RECORD_COMPONENT`
- Add new `RecordComponentInfo` implementation of `AnnotationTarget`. Annotations on record components can be accessed very similarly to the way annotations on method parameters are accessed. I.e., retrieve the class's annotations and identify those with a `target.kind()` of `Kind.RECORD_COMPONENT`. The …
=> Support modules and records

pom.xml, src/main/java/org/jboss/jandex/MethodInternal.java
Backport of #127 to the 2.3 branch, in case we want to do 2.3.1.
=> [2.3] fix MethodInternal.equals and hashCode

src/main/java/org/jboss/jandex/MethodInternal.java
The `MethodInternal` objects are usually interned, so their
equality and hash code must be correct. Unfortunately, prior
to this commit, the `defaultValue` field was ignored, leading
to `MethodInternal` objects being shared when they shouldn't.
=> fix MethodInternal.equals and hashCode

src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/BasicTestCase.java
In #115 I missed testing the case where a class loaded by the bootstrap `ClassLoader` returns `null` for `Class#getClassLoader`. This change will load using an absolute resource path via `Class#getResourceAsStream`.
=> Load class data stream directly from `Class#getResourceAsStream`

src/main/java/org/jboss/jandex/Indexer.java, src/main/java/org/jboss/jandex/Main.java, src/test/java/org/jboss/jandex/test/ClassInfoMemberPositionTestCase.java
Is generally a bad practice to depend on the default platform locale, so this PR use Locale.ROOT for [String.format()](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#format-java.util.Locale-java.lang.String-java.lang.Object...-) calls.
=> Use Locale.ROOT in String.format()

core/src/main/java/org/jboss/jandex/AnnotationInstance.java, core/src/main/java/org/jboss/jandex/FieldInternal.java, core/src/main/java/org/jboss/jandex/Index.java, core/src/main/java/org/jboss/jandex/IndexReader.java, core/src/main/java/org/jboss/jandex/IndexReaderImpl.java, core/src/main/java/org/jboss/jandex/IndexReaderV1.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/IndexWriter.java, core/src/main/java/org/jboss/jandex/IndexWriterImpl.java, core/src/main/java/org/jboss/jandex/IndexWriterV1.java, core/src/main/java/org/jboss/jandex/IndexWriterV2.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/MethodInfo.java, core/src/main/java/org/jboss/jandex/MethodInternal.java, core/src/main/java/org/jboss/jandex/RecordComponentInternal.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/test/java/org/jboss/jandex/test/BasicTestCase.java
Fixes #120 - I'm hoping they were not excluded deliberately originally :-) This also includes a refactoring of `processAttributes` to use a switch statement for readability.
=> Read RuntimeInvisible*Annotations in Indexer

core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/Utf8ConstantEncodingTest.java
Constant pool entries of type `CONSTANT_Utf8_info` do not, despite
the name, use the UTF-8 encoding. They use a modified variant
of UTF-8, as specified by `java.io.Data{Input,Output}`.
When decoding these entries, the `Indexer.decodeUtf8Entry` method
interpreted the data as UTF-8. This didn't cause issues, because
the constants are usually human-readable strings that fit the ASCII
table, in which case the two encodings do not differ.
In case of machine-generated content, the difference may easily
occur; for example in case of a string that contains the null
character. One realistic example is the Kotlin standard library
JAR, where the `kotlin/collections/ArraysKt___ArraysKt.class` class
contains a `@KotlinMetadata` annotation whose `d1` member contains
such "weird" string.
The fix is …
=> Fix decoding UTF-8 constant pool entries

src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/Utf8ConstantEncodingTest.java
Constant pool entries of type `CONSTANT_Utf8_info` do not, despite
the name, use the UTF-8 encoding. They use a modified variant
of UTF-8, as specified by `java.io.Data{Input,Output}`.
When decoding these entries, the `Indexer.decodeUtf8Entry` method
interpreted the data as UTF-8. This didn't cause issues, because
the constants are usually human-readable strings that fit the ASCII
table, in which case the two encodings do not differ.
In case of machine-generated content, the difference may easily
occur; for example in case of a string that contains the null
character. One realistic example is the Kotlin standard library
JAR, where the `kotlin/collections/ArraysKt___ArraysKt.class` class
contains a `@KotlinMetadata` annotation whose `d1` member contains
such "weird" string.
The fix is …
=> [2.4] Fix decoding UTF-8 constant pool entries

src/main/java/org/jboss/jandex/NameTable.java, src/test/java/$delimiters$/test/$SurroundedByDelimiters$.java, src/test/java/$pkg/test/$LeadingDelimiter.java, src/test/java/org/jboss/jandex/test/DotNameTestCase.java
Fixes #148 
Prior to #130 , top-level classes with names leading with `$` were parsed as nested classes contained within an empty-name class. Classes could still be retrieved from the index by simple `DotName`s as they were still equal via the `DotName#crossEquals` method.
If this is accepted I can open a separate PR for the `smallrye` branch.
=> [2.4] Support top-level class name with leading inner class delimiter

pom.xml, src/main/java/org/jboss/jandex/Indexer.java, src/test/java/org/jboss/jandex/test/RecordTestCase.java
=> [2.4] Support ClassInfo signature at any position

core/src/main/java/org/jboss/jandex/ClassSummary.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/JarIndexer.java, core/src/main/java/org/jboss/jandex/Main.java, core/src/test/java/org/jboss/jandex/test/BasicTestCase.java, core/src/test/java/org/jboss/jandex/test/BridgeMethodTestCase.java, core/src/test/java/org/jboss/jandex/test/ClassInfoMemberPositionTestCase.java, core/src/test/java/org/jboss/jandex/test/ConstantDynamicTestCase.java, core/src/test/java/org/jboss/jandex/test/InnerClassTypeAnnotationTestCase.java, core/src/test/java/org/jboss/jandex/test/ModifiersTestCase.java, core/src/test/java/org/jboss/jandex/test/ModuleInfoTestCase.java, core/src/test/java/org/jboss/jandex/test/RecordTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeAnnotationTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeParameterBoundTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeUseTestCase.java, core/src/test/java/org/jboss/jandex/test/Utf8ConstantEncodingTest.java, core/src/test/java/org/jboss/jandex/test/util/IndexingUtil.java, maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java
The `Indexer.index()` method used to return `ClassInfo`, which
assumes that no whole-index post-processing is not necessarsy.
Indeed Jandex doesn't do any such post-processing at the moment,
but it seems pretty obvious that it is necessary. Thus, as a first
step, this commit changes this method to return `void`, so that
all `Indexer` callers are forced to call `complete()` before
being able to access any kind of indexed information.
There are 2 kinds of usages of the `Indexer.index()` result of
the `ClassInfo` type in the Jandex project itself: showing some
summary during batch indexing and creating a single-class index
for tests.
For the first use case, a method `indexWithSummary` is added
that returns `ClassSummary`. This is fine and doesn't affect future
index post-processing, because …
=> make Indexer.index() return void

core/src/main/java/org/jboss/jandex/DotName.java, core/src/main/java/org/jboss/jandex/EquivalenceKey.java, core/src/main/java/org/jboss/jandex/Utils.java, core/src/main/java/org/jboss/jandex/WildcardType.java, core/src/test/java/org/jboss/jandex/test/EquivalenceTest.java, core/src/test/java/org/jboss/jandex/test/MyAnnotation.java, core/src/test/java/org/jboss/jandex/test/TooManyMethodParametersTest.java, core/src/test/java/org/jboss/jandex/test/Utf8ConstantEncodingTest.java
=> introduce the notion of equivalence

core/src/main/java/org/jboss/jandex/DotName.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/IndexWriterV2.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/test/java/org/jboss/jandex/test/DotNameComponentizationTest.java, core/src/test/java/org/jboss/jandex/test/DotNameTestCase.java
=> DotName componentization

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/CompositeIndex.java, core/src/main/java/org/jboss/jandex/Index.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/IndexView.java, core/src/main/java/org/jboss/jandex/IndexWriterV2.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/CompositeTestCase.java, core/src/test/java/org/jboss/jandex/test/SubtypesLookupTest.java
This is technically a breaking change, but only for users who
extend/implement the `IndexView` interface. Callers are fine.
It is tempting to fix `IndexView.getKnownDirectImplementors`
to no longer return subinterfaces, but we refrain from doing so
to maintain behavioral compatibility.
This change requires persistent format version bump. That has already
happened on the `smallrye` branch, so this commit doesn't bump
again, but note that this commit can't be backported to Jandex 2.x.
Resolves #65
=> add IndexView.getKnownDirectSubinterfaces and getAllKnownSubinterfaces

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/IndexWriterV2.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/NestedClassesTest.java
This allows navigating from `ClassInfo` to its member classes.
The `memberClasses()` method returns a set of `DotName` objects,
because member classes don't necessarily have to be present in
the index. It is a responsibility of the caller to retrieve
a `ClassInfo` of each member class from the index and handle
possible absence.
This change requires persistent format version bump. That has already
happened on the `smallrye` branch, so this commit doesn't bump
again, but note that this commit can't be backported to Jandex 2.x.
Resolves #180
=> add ClassInfo.memberClasses

benchmarks/pom.xml, benchmarks/run-benchmarks.sh, benchmarks/src/main/java/org/jboss/jandex/Lump.java, benchmarks/src/main/java/org/jboss/jandex/chart/AllBenchmarks.java, benchmarks/src/main/java/org/jboss/jandex/chart/BenchmarksForVersion.java, benchmarks/src/main/java/org/jboss/jandex/chart/ChartGenerator.java, benchmarks/src/main/java/org/jboss/jandex/json/BenchmarkDto.java, benchmarks/src/main/java/org/jboss/jandex/json/PrimaryMetricDto.java, benchmarks/src/test/java/org/jboss/jandex/DotNameEqualsBenchmark.java, benchmarks/src/test/java/org/jboss/jandex/IndexAccessBenchmark.java, core/src/main/java/org/jboss/jandex/DotName.java, pom.xml
According to the results there is no significant difference in performance of `DotName.crossEquals()` and `DotName.componentizedEquals()` and so it does not make sense to maintain two dedicated methods.
=> Introduce microbenchmarks, replace DotName.crossEquals() with DotName.componentizedEquals() 

maven-plugin/src/it/defaultFileset/verify.groovy, maven-plugin/src/it/filesets/verify.groovy, maven-plugin/src/it/multipleIndices/pom.xml, maven-plugin/src/it/multipleIndices/src/main/java/org/jboss/jandex/maven/multipleIndices/SomeClass.java, maven-plugin/src/it/multipleIndices/verify.groovy, maven-plugin/src/it/noFileset/pom.xml, maven-plugin/src/it/noFileset/verify.groovy, maven-plugin/src/main/java/org/jboss/jandex/maven/FileSet.java, maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java
Previously, the Maven plugin generated one index for each file set,
which is pretty counter-intuitive. With this change, all file sets
contribute to the same index. If the user wants to generate multiple
indices, they should define multiple executions of the Maven plugin.
Fixes #138.
=> Make the Maven plugin generate a single index per execution

.github/workflows/release.yml, core/src/main/java/org/jboss/jandex/JandexReflection.java, core/src/test/java/org/jboss/jandex/test/JandexReflectionTest.java
=> add JandexReflection for runtime loading of classes corresponding to Jandex objects

core/src/main/java/org/jboss/jandex/GenericSignatureParser.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/SignatureSharingTest.java
The generic signature parser used to forget previously encountered
element-level type parameters when parsing a signature of a new
element, and previously encountered class-level type parameters when
parsing a signature of a new class. This leaves a hole: previously
encountered element-level type parameters could be used when
parsing a signature of a new class. When parsing a signature of
a new class, previously encountered element-level type parameters
must also be forgotten, to prevent wrong sharing.
Fixes #98
=> Fix wrong type parameter sharing in generic signature parser

core/src/main/java/org/jboss/jandex/CompositeIndex.java, core/src/main/java/org/jboss/jandex/DotName.java, core/src/main/java/org/jboss/jandex/Index.java, core/src/main/java/org/jboss/jandex/IndexView.java, core/src/test/java/org/jboss/jandex/test/DotNameTestCase.java, core/src/test/java/org/jboss/jandex/test/PackagesTest.java
Two new methods, `getClassesInPackage` and `getSubpackages`, are added
to `IndexView`. Unlike other index methods, these don't expect to have
precomputed answers stored in the persistent format. The packages info
can be recomputed rather easily from the full set of known classes, so
these methods just initialize their "index" on demand. First call then
may be slow, but subsequent calls will be fast.
Resolves #96
=> add methods to Index to work with packages

.github/workflows/ci.yml, core/src/main/java/org/jboss/jandex/DotName.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/test/java/org/jboss/jandex/test/BridgeMethodTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeAnnotationOnLocalClassTypeTest.java, core/src/test/java/org/jboss/jandex/test/TypeAnnotationTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeParameterBoundTestCase.java
This includes several things:
- `Type.toString()` no longer shows type annotations before a package name,
because package names can't be annotated;
- type annotations on types that are local classes are supported properly;
- type annotations on outermost annotable types are supported properly.
Fixes #161.
=> improve type annotations handling

core/src/main/java/org/jboss/jandex/IndexReader.java, core/src/main/java/org/jboss/jandex/IndexReaderImpl.java, core/src/main/java/org/jboss/jandex/IndexReaderV1.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java
The data version number wasn't kept up to date, most likely because
noone even knows there was a difference between index version and
data version. This commit removes the notion of data version and
intentionally conflates the index format version and data version.
It's not like Jandex has ever changed its persistent format without
also changing the data contract...
Resolves #181
=> remove the notion of data version

core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/IndexWriterV2.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/main/java/org/jboss/jandex/TypeVariable.java, core/src/main/java/org/jboss/jandex/UnresolvedTypeVariable.java, core/src/test/java/org/jboss/jandex/test/TypeParameterBoundTestCase.java, core/src/test/java/org/jboss/jandex/test/UnboundedWildcardTest.java
This commit includes regularization of string representation of types,
which is how the unfaithfulness was discovered in the first place.
=> Serialize unbounded wildcards faithfully

core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/RecordTestCase.java, test-data/src/main/java/test/RecordExample.java
It seems javac has a bug when emitting a compact constructor of a record
that declares a component whose type has type annotations. For example:
public record MyRecord(List<@NotEmpty String> list) {
public MyRecord {
}
}
In this case, javac emits a type annotation whose `target_type` is 0x13
(that is, the type annotation is supposed to target a field). That is wrong.
My guess is that javac simply copies the type from the implicitly declared
component field, together with type annotations, into the implicitly declared
parameter list of the compact constructor. (On the other hand, type annotations
on the implicitly declared accessor methods are correct.)
With this commit, Jandex ignores such erroneous type annotations.
Fixes #218
=> Workaround for wrong type annotations on compact record constructor

core/src/main/java/org/jboss/jandex/ArrayType.java, core/src/main/java/org/jboss/jandex/FieldInfo.java, core/src/main/java/org/jboss/jandex/FieldInternal.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/MethodInfo.java, core/src/main/java/org/jboss/jandex/MethodInternal.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/RecordComponentInfo.java, core/src/main/java/org/jboss/jandex/RecordComponentInternal.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/main/java/org/jboss/jandex/TypeVariable.java, core/src/main/java/org/jboss/jandex/UnresolvedTypeVariable.java, core/src/main/java/org/jboss/jandex/WildcardType.java, core/src/test/java/org/jboss/jandex/test/BasicTestCase.java, core/src/test/java/org/jboss/jandex/test/TransitiveTypeParameterBoundsTest.java, core/src/test/java/org/jboss/jandex/test/TransitiveTypeVariablesTest.java, core/src/test/java/org/jboss/jandex/test/TypeAnnotationTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeToStringTest.java, core/src/test/java/org/jboss/jandex/test/TypeToStringWithAnnotationsTest.java
This commit builds on existing support for propagating type annotations
on type parameter bounds. After the existing type annotations on type
parameter bounds propagation pass, a second pass is added that propagates
type annotations on all remaining type variables.
As part of this commit, the string representation of types is improved.
The `Type.toString()` method now has an overload that takes a "simple"
flag. This flag is used to make type variables not append their bounds
into their string representation. With this, the string representation
of declarations and composite types look much closer to the corresponding
Java source code.
=> Propagate type annotations on all type variables + improve Type.toString()

core/src/main/java/org/jboss/jandex/AnnotationTarget.java, core/src/main/java/org/jboss/jandex/DotName.java
In Jandex 3.0.0, we added shortcut methods to `IndexView` so that users
don't have to always create an instance of `DotName`. These methods
accept `String` (which is wrapped into `DotName`) and even `Class<?>`
(whose `getName()` is wrapped into `DotName`).
In this commit, we add similar shortcuts to `DotName.createSimple()`
and all annotation access methods on `AnnotationTarget`.
=> Add String- and Class-accepting shortcuts

core/src/main/java/org/jboss/jandex/TypeVariable.java
Previous implementation of this method was wrong in case the type variable has an implicit bound of `Object`. To conserve memory, `TypeVariable` stores the information whether the first bound is implicitly `Object` as the most significant bit of the `hash` field, which also serves as a hash code cache.
Specifically, if the type variable has an implicit `Object` bound, the MSB is set to `1`, otherwise it is set to `0`. When it's `1`, the `hashCode()` method used to return one value when first called and a different value for subsequent calls.
This is because the beginning of `hashCode()` looks like this:
int hash = this.hash & HASH_MASK;
if (hash != 0) {
return hash;
}
When the hash code has already been computed, the method returns the stored value, properly masked to always have a `0` at …
=> Fix the implementation of `TypeVariable.hashCode()`

core/src/main/java/org/jboss/jandex/AnnotationInstance.java, core/src/main/java/org/jboss/jandex/ArrayType.java, core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/FieldInfo.java, core/src/main/java/org/jboss/jandex/FieldInternal.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/Interned.java, core/src/main/java/org/jboss/jandex/MethodInfo.java, core/src/main/java/org/jboss/jandex/MethodInternal.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/PrimitiveType.java, core/src/main/java/org/jboss/jandex/RecordComponentInternal.java, core/src/main/java/org/jboss/jandex/StrongInternPool.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/main/java/org/jboss/jandex/TypeTarget.java, core/src/main/java/org/jboss/jandex/TypeVariable.java, core/src/main/java/org/jboss/jandex/TypeVariableReference.java, core/src/main/java/org/jboss/jandex/UnresolvedTypeVariable.java, core/src/main/java/org/jboss/jandex/WildcardType.java, core/src/test/java/org/jboss/jandex/test/TypeEqualityTest.java, core/src/test/java/org/jboss/jandex/test/TypeEqualityWithAnnotationsTest.java
=> Restore structural equality/hash code of the `Type` hierarchy

.github/workflows/release.yml, core/src/test/java/org/jboss/jandex/test/BytecodeVersionTest.java, maven-plugin/pom.xml, maven-plugin/src/test/java/org/jboss/jandex/maven/BytecodeVersionTest.java, test-data/pom.xml
Previously, the `test-data` module was always built using a second JDK downloaded during build using a Maven plugin. This is hostile to downstream rebuilds in an air-gapped environment and makes the release process more complex and fragile for no good reason.
With this commit, a second JDK is only downloaded if the "current" JDK is older than 17. If the "current" JDK is 17+, it is used to build all modules, including `test-data`. We still want to make sure that the core Jandex library, as well as the Maven plugin, produce Java 8 bytecode. For that reason, this commit adds an automated test to both modules which verifies that the class file version of some class is `52` (Java 8).
Also, this commit changes the JDK version used for release to 17, to eat our own dog food.
Fixes #264
=> Improve how the `test-data` module is built using JDK 17

pom.xml
When compiling with JDK 8, we still need to use `-source` and `-target`, because JDK 8 doesn't know the `--release` option. However, with JDK 9+, it is better to use `--release`, which not only instructs the compiler to treat the source code as Java 8 and emit Java 8 bytecode, but also compiles against JDK 8 core library signatures.
This is a follow-up on #265 and is a part of the resolution of #264.
=> Use the `--release` option when compiling on JDK 9+

core/src/main/java/org/jboss/jandex/ClassType.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java
It has been possible to create a new instance of `ClassType` using `Type.create()`, but using `ClassType.create()` is often more convenient.
Additionally, this commit improves `ParameterizedType` documentation regarding cases when `ParameterizedType` is used to represent a class type enclosed in a parameterized or type-annotated type.
=> Add ClassType.create()

core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/test/java/org/jboss/jandex/test/KotlinTypeAnnotationWrongTypePathTest.java, core/src/test/java/org/jboss/jandex/test/TooManyMethodParametersTest.java
=> Add workaround for wrong type annotation path generated by Kotlin

core/src/main/java/org/jboss/jandex/Indexer.java
To propagate type annotations across nested classes, we sort the entire set of indexed classes so that outer classes come before inner classes. We don't really care about ordering between classes that are not enclosed in one another. In other words, if we consider the equivalence relation of "be enclosed in" (where we consider a class to be enclosed in itself, so that the relation is reflexive and hence indeed equivalence), we must only sort the equivalence classes of this relation, individually. That is, we define partial order on classes.
However, to perform that sort, we use the sorting routine in the JDK, which uses the order defined by a `Comparator`, and that order must be total. In this commit, we define a total order between classes like so:
1. For each pair of classes A and B:
2. …
=> Fix class ordering when propagating type annotations

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/Descriptor.java, core/src/main/java/org/jboss/jandex/DescriptorReconstruction.java, core/src/main/java/org/jboss/jandex/DotName.java, core/src/main/java/org/jboss/jandex/FieldInfo.java, core/src/main/java/org/jboss/jandex/GenericSignature.java, core/src/main/java/org/jboss/jandex/GenericSignatureReconstruction.java, core/src/main/java/org/jboss/jandex/MethodInfo.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/RecordComponentInfo.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/test/java/org/jboss/jandex/test/DescriptorReconstructionTest.java, core/src/test/java/org/jboss/jandex/test/DotNameTestCase.java, core/src/test/java/org/jboss/jandex/test/GenericSignatureReconstructionTest.java, core/src/test/java/org/jboss/jandex/test/data/ClassInheritance.java, core/src/test/java/org/jboss/jandex/test/data/OuterParam.java, core/src/test/java/org/jboss/jandex/test/data/OuterParamBound.java, core/src/test/java/org/jboss/jandex/test/data/OuterRaw.java
This API includes type variable substitution, which is used on several places in Quarkus. If the substitution function returns a type for some type variable identifier, the reconstructed descriptor/signature contains a descriptor/signature of the provided type instead of the original type variable.
=> Add API for reconstructing descriptors and generic signatures

.github/workflows/ci.yml, .github/workflows/release.yml
- enforce Maven version, because the impsort Maven plugin is not compatible with Maven 3.9
- shorten the CI job description
=> Improve GitHub Actions setup

core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/LambdaSignatureTest.java
In case an invalid generic signature appears in the bytecode, indexing fails with an exception. This is unfriendly, because ECJ emits invalid generic signatures on pretty basic code (a synthetic static method generated for a lambda), so ECJ-generated code cannot be indexed.
This commit simply ignores a generic signature that cannot be parsed.
Fixes #32
=> Ignore invalid generic signatures during indexing

pom.xml
Per: https://maven.apache.org/guides/mini/guide-reproducible-builds.html
* Updates maven-bundle-plugin to 5.1.8 (which removes the `Bnd-LastModified` field from the manifest)
* Adds `project.build.outputTimestamp` to the root pom,  the release plugin will update this value when preparing a release
NOTE: The `test-data` build is NOT reproducible as the jar is patched out of band using the `jar` command
=> Build generates reproducible jars

.github/workflows/ci.yml
Temurin doesn't seem to have a 21-ea release available, so that will have to wait for later.
=> Update Java versions in CI: remove 19 and 20-ea, add 20

core/src/main/java/org/jboss/jandex/AnnotationInstance.java, core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/FieldInternal.java, core/src/main/java/org/jboss/jandex/ImmutableArrayList.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/MethodInternal.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/RecordComponentInternal.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/main/java/org/jboss/jandex/TypeVariable.java
This commit replaces `Collections.unmodifiableList(Arrays.asList(array))` with `new ImmutableArrayList<>(array)`, where `ImmutableArrayList` is a simple implementation of an immutable array-backed list. This reduces the number of allocations from 2 to 1 on many places in the code.
Additionally, this commit slightly improves javadoc of some methods in the `AnnotationInstance` class.
=> Reduce allocations when creating immutable array-backed lists

core/src/main/java/org/jboss/jandex/AnnotationInstance.java, core/src/main/java/org/jboss/jandex/FieldInternal.java, core/src/main/java/org/jboss/jandex/MethodInternal.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/RecordComponentInternal.java, core/src/main/java/org/jboss/jandex/TypeVariable.java, core/src/test/java/org/jboss/jandex/test/AnnotationInstanceTest.java
The `AnnotationInstance.equals()` method provides _equality_. Two annotation instances are equal if, among others, they have identical annotation target. This is often not necessary. Therefore, this commit adds the `equivalentTo()` method, which provides _equivalence_. Two annotation instances are equivalent if they have the same name (the same annotation type) and the same members. No attention is paid to the annotation target.
=> Establish the notion of annotation instance equivalence

maven-plugin/src/it/indexVersion/pom.xml, maven-plugin/src/it/indexVersion/src/main/java/org/jboss/jandex/maven/indexVersion/SomeClass.java, maven-plugin/src/it/indexVersion/verify.groovy, maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java
=> Allow configuring persistent index format version in the Maven plugin

core/src/main/java/org/jboss/jandex/IndexWriterV2.java, doc/modules/ROOT/pages/index.adoc
Jandex 3 added a new kind of types, type variable references. At that time, the index serialization code was not adjusted for serialization to an older version in case a type variable reference is present. Therefore, a Jandex 2 version of an index produced by Jandex 3 is not actually readable by Jandex 2.
Fortunately, there's a simple fix. What Jandex 3 represents as a type variable reference, Jandex 2 always represents as an unresolved type variable. Hence, with this commit, Jandex 3 simply serializes a type variable reference as an unresolved type variable when producing an index of an older versions.
=> restore serialization compatibility with Jandex 2

maven-plugin/src/it/jar/verify.groovy, maven-plugin/src/main/java/org/jboss/jandex/maven/JandexJarGoal.java
support directory in jar,  classloader method: classloader.getResource(entryName) when the entryName is a drectory ,this method would return null.In some opensource tools use this feature to load the resouces in the same folder 
would faile
Resolves #314
=> support directory in jar

core/src/main/java/org/jboss/jandex/AnnotationInstance.java
The `AnnotationInstance.equals()` method considers two annotations that are basically the same as distinct if they don't have the same `target`. However, the `AnnotationInstance.hashCode()` method does not take the `target` into account at all, which leads to hash table collisions. This commit uses the `AnnotationTarget` information to spread out the `AnnotationInstance` hash code to make collisions less likely.
=> improve AnnotationInstance.hashCode()

src/main/java/org/jboss/jandex/AnnotationInstance.java
The `AnnotationInstance.equals()` method considers two annotations that are basically the same as distinct if they don't have the same `target`. However, the `AnnotationInstance.hashCode()` method does not take the `target` into account at all, which leads to hash table collisions. This commit uses the `AnnotationTarget` information to spread out the `AnnotationInstance` hash code to make collisions less likely.
=> [2.4] improve AnnotationInstance.hashCode()

core/src/main/java/org/jboss/jandex/AnnotationInstance.java
The `AnnotationInstance.equals()` method considers two annotations that are basically the same as distinct if they don't have the same `target`. However, the `AnnotationInstance.hashCode()` method does not take the `target` into account at all, which leads to hash table collisions. This commit uses the `AnnotationTarget` information to spread out the `AnnotationInstance` hash code to make collisions less likely.
=> [3.0] improve AnnotationInstance.hashCode()

core/src/main/java/org/jboss/jandex/GenericSignatureParser.java, core/src/test/java/org/jboss/jandex/test/FieldWithPrimitiveTypeSignatureTest.java
The grammar for generic signatures in the JVMS is pretty clear that a signature for a field is a reference type signature. However, there are class files in the wild that contain a primitive type signature for a field. This commit makes that acceptable in Jandex, even though it technically isn't valid bytecode.
Fixes #338
=> allow primitive type signatures on fields

core/src/main/java/org/jboss/jandex/AnnotationInstance.java, core/src/main/java/org/jboss/jandex/AnnotationInstanceEquivalenceProxy.java, core/src/test/java/org/jboss/jandex/test/AnnotationInstanceTest.java
An equivalence proxy is like an equivalence key (that is, its `equals()` and `hashCode()` implement equivalence instead of equality), but it also holds and provides access to the original (delegate) object.
=> add an equivalence proxy for AnnotationInstance

maven-plugin/pom.xml, pom.xml
This updates the plugins used in the project, particularly the plexus-utils update is important as it fixes a false difference detected with CachingOutputStream/CachingWriter when streams are flushed.
=> Update plugin dependencies

core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/ClassOrderWhenPropagatingTypeParameterBoundsTest.java, core/src/test/java/org/jboss/jandex/test/util/TotalOrderChecker.java
To propagate type annotations across nested classes, we sort the entire set of indexed classes so that outer classes come before their inner classes. We don't really care about ordering between classes that are not members of the same nest (using the JEP 181 terminology). That is, we only need a partial order on classes.
However, to perform that sort, we use the sorting routine in the JDK, which uses the order defined by a `Comparator`, and that order must be total.
To define a total order, this commit takes a completely opposite approach. We compute a nesting level for each class (where a top-level class has a nesting level of 0, a class nested in a top-level class has a nesting level of 1, etc.) and sort by the nesting level. For equal nesting levels, we sort by the class name. This …
=> Fix class ordering when propagating type annotations, take two

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/test/java/org/jboss/jandex/test/BasicTestCase.java
=> Add ClassInfo.method(String, List<Type>)

core/src/main/java/org/jboss/jandex/GenericSignatureParser.java, core/src/main/java/org/jboss/jandex/IndexReaderV2.java, core/src/main/java/org/jboss/jandex/IndexWriterV2.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/main/java/org/jboss/jandex/TypeVariableReference.java, doc/modules/ROOT/pages/index.adoc
=> Reduce hash collisions when interning type variable references

core/src/main/java/org/jboss/jandex/CompositeIndex.java, core/src/main/java/org/jboss/jandex/EmptyIndex.java, core/src/main/java/org/jboss/jandex/Index.java, core/src/main/java/org/jboss/jandex/IndexView.java, core/src/main/java/org/jboss/jandex/StackedIndex.java, core/src/test/java/org/jboss/jandex/test/IndexNavigationTest.java, core/src/test/java/org/jboss/jandex/test/StackedIndexTest.java, core/src/test/java/org/jboss/jandex/test/util/IOUtil.java
=> Add empty and stacked indexes

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/IndexView.java, core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/KnownUsersTest.java
See also https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/hibernate.20reactive/near/424410591
=> improve `Index[View].getKnownUsers()`

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/Utils.java
I'm working on a heap dump and Eclipse MAT complained that there was a lot of empty HashMaps around. I had a closer look and a lot of them were due to the Map kept in ClassInfo and this one looked like the most plausible culprit.
Now, in Quarkus, the Jandex index is just around for building the application but it looks like an easy win.
I also handled the size 1 case but I'm not sure it's worth the hassle as long as we stick to Java 8.
@Ladicek this is not to merge as is, it was more to get your feedback with a concrete explanation. 
The following screenshot is a query of the empty HashMaps in the heap dump.
Note that it's the same in the KeySet entry that is at the top.
=> Avoid having a ton of empty HashMaps in memory

maven-plugin/src/main/java/org/jboss/jandex/maven/JandexJarGoal.java
If you're happy with this change to add the indexVersion parameter to the jandex-jar goal (it's already present in the jandex goal), then it would be appreciated if you could apply this change to the base repository either via this pull request, or independently.
=> Added indexVersion parameter to the jandex-jar goal

.github/workflows/prepare-release.yml, .github/workflows/release.yml, .github/workflows/review-release.yml
- checkout the originating git ref instead of the exact commit
- reuse the `pages.yml` workflow instead of copying it
- remove two useless `run-name` configurations
=> Various improvements to the release process

core/src/main/java/org/jboss/jandex/JandexReflection.java, core/src/test/java/org/jboss/jandex/test/JandexReflectionTest.java
The `loadType()` method returns an implementation of `java.lang.reflect.Type`.
If possible, it is compatible with the JDK implementation, in the sense that
`equals()` and `hashCode()` work as expected. Unfortunately, the JDK makes
that impossible if the type contains type variables.
=> Add JandexReflection.loadType()

core/src/main/java/org/jboss/jandex/ArrayType.java, core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/ParameterizedType.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/main/java/org/jboss/jandex/TypeVariable.java, core/src/main/java/org/jboss/jandex/WildcardType.java, core/src/test/java/org/jboss/jandex/test/RecordTestCase.java, core/src/test/java/org/jboss/jandex/test/TypeNameTest.java, core/src/test/java/org/jboss/jandex/test/TypeWithoutAnnotationsTest.java, test-data/src/main/java/test/Record0WithCompactCanonicalCtor.java, test-data/src/main/java/test/Record0WithCustomCanonicalCtor.java, test-data/src/main/java/test/Record0WithDefaultCanonicalCtor.java, test-data/src/main/java/test/Record1WithCompactCanonicalCtor.java, test-data/src/main/java/test/Record1WithCustomCanonicalCtor.java, test-data/src/main/java/test/Record1WithDefaultCanonicalCtor.java, test-data/src/main/java/test/Record2WithCompactCanonicalCtor.java, test-data/src/main/java/test/Record2WithCustomCanonicalCtor.java, test-data/src/main/java/test/Record2WithDefaultCanonicalCtor.java, test-data/src/main/java/test/RecordWithBuggyAnnotation.java, test-data/src/main/java/test/RecordWithDefaultCanonicalCtor.java, test-data/src/main/java/test/RecordWithNoComponentsAndCompactCanonicalCtor.java, test-data/src/main/java/test/RecordWithNoComponentsAndCustomCanonicalCtor.java, test-data/src/main/java/test/RecordWithNoComponentsAndDefaultCanonicalCtor.java
This method had 2 flaws:
- in case of 1 record component, it never worked, because we don't store record component positions in case there's just one;
- it compared types including annotations, which should generally work, but javac sometimes emits type annotations incorrectly.
This commit fixes those issues:
- in case of 1 record component, it no longer looks at component positions, because it's not necessary;
- it compares types after removing all type annotations, which guards against those javac bugs.
=> fix ClassInfo.canonicalRecordConstructor()

core/src/main/java/org/jboss/jandex/Indexer.java, core/src/test/java/org/jboss/jandex/test/ClassAndRuntimeTypeAnnotationsOnMethodTest.java, core/src/test/java/org/jboss/jandex/test/RecordTestCase.java, test-data/src/main/java/test/MyClassAnnotation.java, test-data/src/main/java/test/RecordWithDifferentVisibilityAnnotation.java
In case a single type annotation target (such as a `MethodInfo`) has multiple type annotations, some of them runtime-retained and some class-retained, all annotations of one kind are lost.
This is because `Indexer.processTypeAnnotations()` was written with the assumption that it is only called once for any given target. This was true in Jandex 2, which only supported runtime-retained annotations, but since Jandex 3.0, class-retained annotations are supported as well. Hence, the method can legally be called twice for any given target.
Fortunately, this issue doesn't exist for non-type annotations.
=> fix losing type annotations with different visibility

core/src/main/java/org/jboss/jandex/CompositeIndex.java, core/src/main/java/org/jboss/jandex/EmptyIndex.java, core/src/main/java/org/jboss/jandex/Index.java, core/src/main/java/org/jboss/jandex/IndexView.java, core/src/main/java/org/jboss/jandex/StackedIndex.java, core/src/test/java/org/jboss/jandex/test/AnnotationOverlayTest.java, core/src/test/java/org/jboss/jandex/test/IndexNavigationTest.java, core/src/test/java/org/jboss/jandex/test/SubtypesLookupTest.java
The `getKnownDirectImplementations()` method is different to `getKnownDirectImplementors()` in that it doesn't return direct subinterfaces of the given interface.
The `getAllKnownImplementations()` method is not different to `getAllKnownImplementors()`, it only exists for symmetry.
The previous methods, `getKnownDirectImplementors()` and `getAllKnownImplementors()`, are deprecated now.
=> add IndexView.getKnownDirectImplementations() and getAllKnownImplementations()

core/src/main/java/org/jboss/jandex/ClassInfo.java, core/src/main/java/org/jboss/jandex/IndexView.java, core/src/main/java/org/jboss/jandex/IndexWriter.java, core/src/main/java/org/jboss/jandex/WildcardType.java
All `@Deprecated` program elements that are publicly accessible now have a `@deprecated` section in their javadoc.
Fixes #519
=> add missing deprecation notices

core/pom.xml, core/src/main/module/module-info.java, pom.xml
Since Jandex is still a Java 8 project, we cannot add `module-info.java` to `src/main/java` and build it using javac. Instead, we put the module descriptor into a separate directory (`src/main/module`) and use Moditect to build it (into `module-info.class`).
Fixes #514
=> add module descriptor

core/src/main/java/org/jboss/jandex/ClassType.java, core/src/main/java/org/jboss/jandex/DotName.java, core/src/main/java/org/jboss/jandex/EquivalenceKey.java, core/src/main/java/org/jboss/jandex/JandexReflection.java, core/src/main/java/org/jboss/jandex/TypeVariableReference.java, core/src/test/java/org/jboss/jandex/test/EquivalenceKeyTest.java
Primitive types and `java.*` class types are very commonly used and there is a limited number of them. Therefore, we can intern them safely (growth of the interning cache is naturally bounded) and improve allocation rate significantly.
Further, this commit removes all calls to `Objects.hash()`, because each call allocates an array. It is especially useless when called with just one element.
Co-authored-by: Guillaume Smet <guillaume.smet@gmail.com>
=> intern `EquivalenceKey`s for primitive types and class types of `java.*`

core/src/main/module/module-info.java, gizmo2/pom.xml, gizmo2/src/main/java/org/jboss/jandex/gizmo2/Jandex2Gizmo.java, gizmo2/src/main/module/module-info.java, gizmo2/src/test/java/org/jboss/jandex/gizmo2/Jandex2GizmoTest.java, pom.xml
The `gizmo2` module is added which hosts the Gizmo 2 integration. It depends both on Jandex (core) and Gizmo 2. Since Gizmo 2 is a Java 17 project, this new module is also a Java 17 project. The rest of Jandex remains on Java 8.
The `Jandex2Gizmo` class contains `static` methods to create Gizmo types (`ClassDesc`, `GenericType` etc.) from Jandex types (`DotName`, `Type` etc.).
Resolves #544
=> add Gizmo 2 integration

core/src/main/java/org/jboss/jandex/ArrayType.java, core/src/main/java/org/jboss/jandex/ClassType.java, core/src/main/java/org/jboss/jandex/DotName.java, core/src/test/java/org/jboss/jandex/test/ArrayTypeTest.java
Names of the following single-dimensional array types are cached:
- primitive types
- primitive wrapper classes
- `Object`, `String`, `Class`, `Annotation` class types
Further, names of the following single-dimensional array types are precomputed:
- other `java.*` class types
Other array types compute their name lazily, when `name()` is called.
Fixes #560
=> cache and precompute array type names for the most common cases

core/src/main/java/org/jboss/jandex/ArrayType.java, core/src/test/java/org/jboss/jandex/test/ArrayTypeTest.java
In my case, it was still responsible for quite a lot of allocations.
It allows to handle T[] as [Ljava.lang.Object; more efficiently.
This is a follow-up of https://github.com/smallrye/jandex/pull/562 .
=> Precompute names for 1D arrays of parameterized types and type variables

core/src/main/java/org/jboss/jandex/AnnotationInstance.java, core/src/test/java/org/jboss/jandex/test/MutableAnnotationOverlayTest.java
We avoid going from byte[] to String to compute the hashCode of method names and field names.
=> Reduce allocations for AnnotationInstance.hashCode()

core/src/main/java/org/jboss/jandex/FieldInternal.java, core/src/main/java/org/jboss/jandex/MethodInternal.java, core/src/main/java/org/jboss/jandex/RecordComponentInternal.java
Computing a hash code of an `AnnotationInstance` is relatively expensive, but makes little sense as part of a hash code of `FieldInternal`, `MethodInternal` and `RecordComponentInternal`. This is because there should never be fields, methods and record components that are the same except annotations. Further, there's plenty other information in the field/method/record component hash code, so the impact on hash collisions should be minimal.
Resolves #574
=> skip annotations when computing a hash code of fields, methods and record components

core/src/main/java/org/jboss/jandex/FieldInfo.java, core/src/main/java/org/jboss/jandex/MethodInfo.java, core/src/main/java/org/jboss/jandex/MethodSignatureKey.java, core/src/main/java/org/jboss/jandex/PrimitiveType.java, core/src/main/java/org/jboss/jandex/Type.java, core/src/main/java/org/jboss/jandex/Utils.java, core/src/main/java/org/jboss/jandex/VoidType.java, core/src/test/java/org/jboss/jandex/test/MethodSignatureKeyTest.java
Method signature key is an opaque token that only provides equality and hash code. These operations are based on a method signature, that is, the method name, parameter types and return type. Everything else is ignored.
Fixes #561
=> add `MethodSignatureKey`
