smallrye/jandex

README.md

Version should has been changed since final version has been released.

Version information has been changed.

---

src/main/java/org/jboss/jandex/Indexer.java

This is the workaround I'm using for now.
Signed-off-by: Scott Stark <starksm64@gmail.com>

One possible workaround to JANDEX-40

---

src/main/java/org/jboss/jandex/DotName.java
src/test/java/org/jboss/jandex/test/DotNameTestCase.java

Implementation looks great, I just added a couple more tests to improve confidence on the `compareTo`.

Update unit tests to cover Comparator properties as well

---

src/main/java/org/jboss/jandex/Type.java

It's the second time I wish I had them so let's also add these methods to `Type` (same as for fields and methods).

Add annotation() and hasAnnotation() to Type

---

src/test/java/org/jboss/jandex/test/BasicTestCase.java

chore: better assertion messages

---

pom.xml
src/main/java/org/jboss/jandex/Indexer.java
src/test/java/org/jboss/jandex/test/ConstantDynamicTestCase.java

@dmlloyd @n1hility please review
Fixes #68

Ignore Dynamic Class-File Constants. Fixes #68

---

src/main/java/org/jboss/jandex/IndexReaderV2.java

Relates to: https://github.com/quarkusio/quarkus/issues/7923

Ensure class is set for annotation targets of MethodParameterInfo

---

src/main/java/org/jboss/jandex/Main.java

Dumping the index - output the version

---

src/main/java/org/jboss/jandex/ClassInfo.java

The idea was brought up by @mkouba
in https://github.com/quarkusio/quarkus/pull/8321#discussion_r401456592

Add constructors method to ClassInfo

---

src/main/java/org/jboss/jandex/ClassInfo.java
src/main/java/org/jboss/jandex/DotName.java
src/main/java/org/jboss/jandex/FieldInfo.java
src/main/java/org/jboss/jandex/MethodInfo.java
src/main/java/org/jboss/jandex/Modifiers.java
src/test/java/org/jboss/jandex/test/BasicTestCase.java
src/test/java/org/jboss/jandex/test/FieldInfoTestCase.java
src/test/java/org/jboss/jandex/test/ModifiersTestCase.java

This PR builds on top of https://github.com/wildfly/jandex/pull/63 and resolves https://github.com/wildfly/jandex/issues/60 and https://github.com/wildfly/jandex/issues/54.
@MikeEdgar @n1hility If there are no objections I'd liketo close https://github.com/wildfly/jandex/pull/63 in favor of this PR (the commit from Mike is included).

ClassInfo - add isEnum(), isAnnotation() and isSynthetic()

---

src/main/java/org/jboss/jandex/Indexer.java
src/test/java/org/jboss/jandex/test/BasicTestCase.java

Null streams are not indexable

---

src/main/java/org/jboss/jandex/AnnotationValue.java
src/test/java/org/jboss/jandex/test/AnnotationValuesTestCase.java

Override equals()/hashCode() in AnnotationValue.BooleanValue

---

pom.xml
src/main/java/org/jboss/jandex/Indexer.java
src/main/java/org/jboss/jandex/PositionBasedTypeTarget.java
src/main/java/org/jboss/jandex/TypeParameterBoundTypeTarget.java
src/test/java/org/jboss/jandex/test/InnerClassTypeAnnotationTestCase.java

Fixes type annotations on non-generic inner class constructors.

Fix type annotations on non-generic inner class constructors

---

src/main/java/org/jboss/jandex/IndexWriterV2.java
src/main/java/org/jboss/jandex/TypeTarget.java

Fix persistence of null type targets and clarify doc.

Fix persistence of null type targets and clarify doc

---

src/main/java/org/jboss/jandex/FieldInfo.java
src/main/java/org/jboss/jandex/MethodParameterInfo.java

FieldInfo, MethodParameterInfo - implement equals/hashCode

---

src/main/java/org/jboss/jandex/CompositeIndex.java
src/main/java/org/jboss/jandex/Index.java
src/main/java/org/jboss/jandex/IndexReaderV1.java
src/main/java/org/jboss/jandex/IndexReaderV2.java
src/main/java/org/jboss/jandex/IndexView.java
src/main/java/org/jboss/jandex/IndexWriterV2.java
src/main/java/org/jboss/jandex/Indexer.java
src/main/java/org/jboss/jandex/Main.java
src/main/java/org/jboss/jandex/Result.java
src/test/java/org/jboss/jandex/test/BasicTestCase.java
src/test/java/org/jboss/jandex/test/util/LoadIndexAndDumpHeap.java

Add class constant indexing

---

src/main/java/org/jboss/jandex/IndexReaderV1.java
src/main/java/org/jboss/jandex/IndexReaderV2.java
src/main/java/org/jboss/jandex/IndexWriterV1.java
src/main/java/org/jboss/jandex/IndexWriterV2.java

Fixed small typo

---

core/src/main/java/org/jboss/jandex/NameTable.java
core/src/test/java/$delimiters$/test/$SurroundedByDelimiters$.java
core/src/test/java/$pkg/test/$LeadingDelimiter.java
core/src/test/java/org/jboss/jandex/test/DotNameTestCase.java

Support top-level class name with leading inner class delimiter

---

src/main/java/org/jboss/jandex/Indexer.java

[2.4] Make module attributes parsing order-independent

---

.github/workflows/ci.yml
core/src/main/java/org/jboss/jandex/ClassInfo.java
core/src/main/java/org/jboss/jandex/DotName.java
core/src/main/java/org/jboss/jandex/IndexReaderV2.java
core/src/main/java/org/jboss/jandex/IndexWriterV2.java
core/src/main/java/org/jboss/jandex/Indexer.java
core/src/main/java/org/jboss/jandex/MethodInfo.java
core/src/main/java/org/jboss/jandex/MethodInternal.java
core/src/main/java/org/jboss/jandex/MethodParameterInfo.java
core/src/main/java/org/jboss/jandex/PositionBasedTypeTarget.java
core/src/test/java/org/jboss/jandex/test/BasicTestCase.java
core/src/test/java/org/jboss/jandex/test/ImplicitDeclarationsExample.java
core/src/test/java/org/jboss/jandex/test/ImplicitDeclarationsTest.java
core/src/test/java/org/jboss/jandex/test/InnerClassTypeAnnotationTestCase.java
core/src/test/java/org/jboss/jandex/test/SyntheticDeclarationsExample.java
core/src/test/java/org/jboss/jandex/test/SyntheticDeclarationsTest.java
test-data/src/main/java/test/ImplicitDeclarationsExampleSupplement.java
test-data/src/main/java/test/MyAnnotation.java
test-data/src/main/java/test/MyRepeatableAnnotation.java

uniform handling of implicitly declared (aka mandated) and synthetic parameters

---

README.md
maven-plugin/pom.xml
maven-plugin/src/it/defaultFileset/src/main/java/org/jboss/jandex/maven/defaultFileset/SomeClass.java
maven-plugin/src/it/dependencies/pom.xml
maven-plugin/src/it/dependencies/src/main/java/org/jboss/jandex/maven/dependencies/SomeClass.java
maven-plugin/src/it/dependencies/verify.groovy
maven-plugin/src/it/filesets/src/main/java/org/jboss/jandex/maven/filesets/SomeClass.java
maven-plugin/src/it/multipleIndices/src/main/java/org/jboss/jandex/maven/multipleIndices/SomeClass.java
maven-plugin/src/it/noFileset/src/main/java/org/jboss/jandex/maven/noFileset/SomeClass.java
maven-plugin/src/it/smoketest/src/main/java/org/jboss/jandex/maven/smoketest/SomeClass.java
maven-plugin/src/main/java/org/jboss/jandex/maven/ArchiveScanner.java
maven-plugin/src/main/java/org/jboss/jandex/maven/Dependency.java
maven-plugin/src/main/java/org/jboss/jandex/maven/FileSet.java
maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java
pom.xml

Add support for indexing dependencies to the Maven plugin

---

README.md
maven-plugin/src/it/jar/pom.xml
maven-plugin/src/it/jar/src/main/java/org/jboss/jandex/maven/jar/SomeClass.java
maven-plugin/src/it/jar/verify.groovy
maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java
maven-plugin/src/main/java/org/jboss/jandex/maven/JandexJarGoal.java

Add a dedicated goal to the Jandex Maven plugin to [re]index a JAR

---

core/src/main/java/org/jboss/jandex/ArrayType.java
core/src/main/java/org/jboss/jandex/Type.java
core/src/main/java/org/jboss/jandex/UnresolvedTypeVariable.java
core/src/main/java/org/jboss/jandex/WildcardType.java
core/src/test/java/org/jboss/jandex/test/TypeNameTest.java

Also, some type-related javadoc is improved.

fix ArrayType.name() and add test

---

core/src/main/java/org/jboss/jandex/AnnotationInstance.java
core/src/main/java/org/jboss/jandex/AnnotationInstanceBuilder.java
core/src/main/java/org/jboss/jandex/DotName.java
core/src/test/java/org/jboss/jandex/test/AnnotationInstanceBuilderTest.java

add AnnotationInstance.builder()

---

core/src/main/java/org/jboss/jandex/Indexer.java
core/src/main/java/org/jboss/jandex/Main.java
core/src/test/java/org/jboss/jandex/test/ClassInfoMemberPositionTestCase.java

forward-port changes from `master`

---

core/src/main/java/org/jboss/jandex/GenericSignatureParser.java
core/src/test/java/org/jboss/jandex/test/RecursiveTypeParametersTest.java
core/src/test/java/org/jboss/jandex/test/RecursiveTypeParametersWithAnnotationsTest.java

In case a type parameter is recursive, but not recursive in itself,
the generic signature parser used to be confused and enter infinite
regress. This commit fixes that. The fix also simplifies the method
that determines if a type is recursive, so this is a double win.
Fixes #247

fix parsing recursive generic signatures

---

core/src/main/java/org/jboss/jandex/ClassExtendsTypeTarget.java
core/src/main/java/org/jboss/jandex/EmptyTypeTarget.java
core/src/main/java/org/jboss/jandex/Indexer.java
core/src/main/java/org/jboss/jandex/MethodParameterTypeTarget.java
core/src/main/java/org/jboss/jandex/PositionBasedTypeTarget.java
core/src/main/java/org/jboss/jandex/ThrowsTypeTarget.java
core/src/main/java/org/jboss/jandex/TypeParameterBoundTypeTarget.java
core/src/main/java/org/jboss/jandex/TypeParameterTypeTarget.java
core/src/main/java/org/jboss/jandex/TypeTarget.java
core/src/test/java/org/jboss/jandex/test/TransitiveTypeVariablesInInnerSubclassTest.java

Fix type variable propagation

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
dco.txt

* add Code of conduct, contributing and security document
* add Getting Help section to the README
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

Community Standards

---

core/src/main/java/org/jboss/jandex/ClassInfo.java
core/src/main/java/org/jboss/jandex/Indexer.java
core/src/test/java/org/jboss/jandex/test/AnnotationAccessTest.java
core/src/test/java/org/jboss/jandex/test/BasicTestCase.java
core/src/test/java/org/jboss/jandex/test/CompiledWith.java
core/src/test/java/org/jboss/jandex/test/ImplicitDeclarationsTest.java
core/src/test/java/org/jboss/jandex/test/SyntheticDeclarationsTest.java
core/src/test/java/org/jboss/jandex/test/WeirdInnerClassConstructorTest.java
maven-plugin/src/it/someLibraries/pom.xml

Fix adjusting parameter list of weird inner class constructors

---

core/src/main/java/org/jboss/jandex/AnnotationInstanceBuilder.java
core/src/main/java/org/jboss/jandex/AnnotationTarget.java
core/src/main/java/org/jboss/jandex/ArrayType.java
core/src/main/java/org/jboss/jandex/ClassInfo.java
core/src/main/java/org/jboss/jandex/ClassType.java
core/src/main/java/org/jboss/jandex/Declaration.java
core/src/main/java/org/jboss/jandex/EquivalenceKey.java
core/src/main/java/org/jboss/jandex/FieldInfo.java
core/src/main/java/org/jboss/jandex/JandexReflection.java
core/src/main/java/org/jboss/jandex/MethodInfo.java
core/src/main/java/org/jboss/jandex/MethodParameterInfo.java
core/src/main/java/org/jboss/jandex/ParameterizedType.java
core/src/main/java/org/jboss/jandex/RecordComponentInfo.java
core/src/main/java/org/jboss/jandex/TypeTarget.java
core/src/test/java/org/jboss/jandex/test/ArrayTypeTest.java

- Add the notion of "declaration"
- Improve representation of array types
- Add factory methods for `ClassType`
- Add factory methods for `ParameterizedType`
- Simplify implementation of `JandexReflection`

Relatively small but important improvements

---

maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java

Maven plugin: support <indexName> containing a path

---

maven-plugin/src/it/skipForPom/pom.xml
maven-plugin/src/it/skipForPom/verify.groovy
maven-plugin/src/main/java/org/jboss/jandex/maven/JandexGoal.java

skip Jandex Maven plugin execution for POM packaging

---

core/src/main/java/org/jboss/jandex/AnnotationInstance.java
core/src/main/java/org/jboss/jandex/AnnotationOverlay.java
core/src/main/java/org/jboss/jandex/AnnotationOverlayImpl.java
core/src/main/java/org/jboss/jandex/AnnotationTransformation.java
core/src/main/java/org/jboss/jandex/ClassInfo.java
core/src/main/java/org/jboss/jandex/DotName.java
core/src/main/java/org/jboss/jandex/FieldInfo.java
core/src/main/java/org/jboss/jandex/Index.java
core/src/main/java/org/jboss/jandex/MethodInfo.java
core/src/main/java/org/jboss/jandex/MethodParameterInfo.java
core/src/main/java/org/jboss/jandex/MutableAnnotationOverlay.java
core/src/main/java/org/jboss/jandex/MutableAnnotationOverlayImpl.java
core/src/main/java/org/jboss/jandex/RecordComponentInfo.java
core/src/main/java/org/jboss/jandex/Type.java
core/src/test/java/org/jboss/jandex/test/AnnotationOverlayTest.java
core/src/test/java/org/jboss/jandex/test/MutableAnnotationOverlayTest.java
core/src/test/java/org/jboss/jandex/test/MyOtherAnnotation.java

add annotation overlay

---

core/src/main/java/org/jboss/jandex/Index.java
core/src/test/java/org/jboss/jandex/test/ModuleInfoTestCase.java

Fix Index.singleClass() when the passed class file is in fact a module descriptor

---

core/src/main/java/org/jboss/jandex/DotName.java
core/src/main/java/org/jboss/jandex/EquivalenceKey.java
gizmo2/src/main/java/org/jboss/jandex/gizmo2/Jandex2Gizmo.java

I had an hesitation for the AnnotationOverlay. I think it could be valuable but we will also have quite a lot of misses so it would probably require some measurements.

Use an optimistic pattern for CHM caches that will be filled fast
